#language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ifchicken/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true ifchicken/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker_react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-167166056075"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
