#language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ifchicken/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true ifchicken/docker_react npm run test
